apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skov-codes
  namespace: cd-skov-run
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghost/ghost:4.x.x
spec:
  project: default

  source: 
    repoURL: https://github.com/simcax/deploy-skov.codes.git
    targetRevision: HEAD
    path: skov-codes
  destination:
    server: https://kubernetes.default.svc
    namespace: skov-codes-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
