apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skov-codes
  namespace: argocd-skov-run
  annotations:
    argocd-image-updater.argoproj.io/image-list: skov-codes=simcax/skov.codes
    argocd-image-updater.argoproj.io/skov-codes.pull-secret: pullsecret:argocd-skov-run/regcred-skov-codes
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd-skov-run/git-creds 
    argocd-image-updater.argoproj.io/git-branch: master
spec:
  project: default

  source: 
    repoURL: https://github.com/simcax/deploy-skov.codes.git
    targetRevision: HEAD
    path: skov-codes
  destination:
    server: https://kubernetes.default.svc
    namespace: skov-codes-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
